# Generated by Django 3.2.4 on 2021-06-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decription',
            field=models.TextField(default='Lorem ipsum ksdalfjkajlkfajkdfaklsdfdsfkl google product'),
            preserve_default=False,
        ),
    ]
