# Generated by Django 3.2.4 on 2021-06-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
    ]
